### ISSUE TITLE
An error occurs when running on android: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by Sql1901** [NamCkiku/PhotoBrowser.Maui#3]
An error occurs when running on android:
Java.Lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
  in PhotoBrowser.Maui/Platforms/Android/ImageGallery/GallerySlideActivity.cs
  in void OnCreate.

**Comment by NamCkiku** [comment]
add android:theme="@style/ Theme.AppCompat" to Application in file AndroidManifest.xml
