### ISSUE TITLE
Error clang++ MAUI iOS

### ISSUE THREAD

**Issue by mimunoz** [NamCkiku/PhotoBrowser.Maui#4]
Hi everyone,

after install the latest version of the nugget, the build output show this error: Error  : clang++ exited with code 1:
ld: in /Users/miguel/.nuget/packages/mwphotobrowser.ios/1.0.7/lib/net8.0-ios17.2/MWPhotoBrowserBinding.resources/DACircularProgress.a(DACircularProgress-dummy.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/miguel/.nuget/packages/mwphotobrowser.ios/1.0.7/lib/net8.0-ios17.2/MWPhotoBrowserBinding.resources/DACircularProgress.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

MAUI 8
Targeting iOS 17.2 emulator

any help?

**Comment by NamCkiku** [comment]
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
	<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
</PropertyGroup>

 Add to csproj build Simulator
